// Generated from: features/private-packages/api-bypass.feature
import { test } from "../../../steps/fixtures.ts";

test.describe('API endpoints do not leak private skills', () => {

  test.beforeEach('Background', async ({ Given, bddState, e2eContext, publishedPrivateSkill }, testInfo) => { if (testInfo.error) return;
    await Given('Alice has published a private skill "private-access-skill"', null, { bddState, e2eContext, publishedPrivateSkill }); 
  });
  
  test('Publisher can fetch private skill metadata via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await When('Alice calls GET "/api/v1/skills/{skill}" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 200', null, { e2eContext }); 
  });

  test('Outsider gets 404 for private skill metadata via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ Given, When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await Given('Charlie is authenticated but not in Alice\'s organization', null, { thirdUser }); 
    await When('Charlie calls GET "/api/v1/skills/{skill}" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 404', null, { e2eContext }); 
  });

  test('Unauthenticated request gets 404 for private skill metadata', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ When, Then, bddState, e2eContext }) => { 
    await When('an unauthenticated user calls GET "/api/v1/skills/{skill}"', null, { bddState, e2eContext }); 
    await Then('the API response status should be 404', null, { e2eContext }); 
  });

  test('Publisher can list versions via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await When('Alice calls GET "/api/v1/skills/{skill}/versions" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 200', null, { e2eContext }); 
  });

  test('Outsider gets 404 for version listing via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ Given, When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await Given('Charlie is authenticated but not in Alice\'s organization', null, { thirdUser }); 
    await When('Charlie calls GET "/api/v1/skills/{skill}/versions" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 404', null, { e2eContext }); 
  });

  test('Publisher can fetch specific version via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await When('Alice calls GET "/api/v1/skills/{skill}/1.0.0" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 200', null, { e2eContext }); 
  });

  test('Outsider gets 404 for specific version via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ Given, When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await Given('Charlie is authenticated but not in Alice\'s organization', null, { thirdUser }); 
    await When('Charlie calls GET "/api/v1/skills/{skill}/1.0.0" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 404', null, { e2eContext }); 
  });

  test('Publisher can fetch file content via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await When('Alice calls GET "/api/v1/skills/{skill}/1.0.0/files/skills.json" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 200', null, { e2eContext }); 
  });

  test('Outsider gets 404 for file content via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ Given, When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await Given('Charlie is authenticated but not in Alice\'s organization', null, { thirdUser }); 
    await When('Charlie calls GET "/api/v1/skills/{skill}/1.0.0/files/skills.json" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 404', null, { e2eContext }); 
  });

  test('Publisher can fetch star status via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await When('Alice calls GET "/api/v1/skills/{skill}/star" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 200', null, { e2eContext }); 
  });

  test('Outsider gets 404 for star status via API', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ Given, When, Then, bddState, e2eContext, secondUser, thirdUser }) => { 
    await Given('Charlie is authenticated but not in Alice\'s organization', null, { thirdUser }); 
    await When('Charlie calls GET "/api/v1/skills/{skill}/star" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 404', null, { e2eContext }); 
  });

  test('Private skill does not appear in search API for outsider', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ Given, When, Then, And, bddState, e2eContext, secondUser, thirdUser }) => { 
    await Given('Charlie is authenticated but not in Alice\'s organization', null, { thirdUser }); 
    await When('Charlie calls GET "/api/v1/search?q={searchQuery}" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 200', null, { e2eContext }); 
    await And('the API response body should not contain the private skill name', null, { e2eContext }); 
  });

  test('Private skill appears in search API for publisher', { tag: ['@private-packages', '@api-bypass', '@critical'] }, async ({ When, Then, And, bddState, e2eContext, secondUser, thirdUser }) => { 
    await When('Alice calls GET "/api/v1/search?q={searchQuery}" with auth', null, { bddState, e2eContext, secondUser, thirdUser }); 
    await Then('the API response status should be 200', null, { e2eContext }); 
    await And('the API response body should contain the private skill name', null, { e2eContext }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/private-packages/api-bypass.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":10,"pickleLine":12,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":11,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When Alice calls GET \"/api/v1/skills/{skill}\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Alice","children":[]},"parameterTypeName":"word"},{"group":{"start":16,"value":"\"/api/v1/skills/{skill}\"","children":[{"start":17,"value":"/api/v1/skills/{skill}","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 200","stepMatchArguments":[{"group":{"start":34,"value":"200","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":15,"pickleLine":17,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":18,"keywordType":"Context","textWithKeyword":"Given Charlie is authenticated but not in Alice's organization","stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":19,"keywordType":"Action","textWithKeyword":"When Charlie calls GET \"/api/v1/skills/{skill}\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Charlie","children":[]},"parameterTypeName":"word"},{"group":{"start":18,"value":"\"/api/v1/skills/{skill}\"","children":[{"start":19,"value":"/api/v1/skills/{skill}","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 404","stepMatchArguments":[{"group":{"start":34,"value":"404","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":21,"pickleLine":23,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":24,"keywordType":"Action","textWithKeyword":"When an unauthenticated user calls GET \"/api/v1/skills/{skill}\"","stepMatchArguments":[{"group":{"start":34,"value":"\"/api/v1/skills/{skill}\"","children":[{"start":35,"value":"/api/v1/skills/{skill}","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":23,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 404","stepMatchArguments":[{"group":{"start":34,"value":"404","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":26,"pickleLine":28,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"When Alice calls GET \"/api/v1/skills/{skill}/versions\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Alice","children":[]},"parameterTypeName":"word"},{"group":{"start":16,"value":"\"/api/v1/skills/{skill}/versions\"","children":[{"start":17,"value":"/api/v1/skills/{skill}/versions","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 200","stepMatchArguments":[{"group":{"start":34,"value":"200","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":31,"pickleLine":33,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":34,"keywordType":"Context","textWithKeyword":"Given Charlie is authenticated but not in Alice's organization","stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":35,"keywordType":"Action","textWithKeyword":"When Charlie calls GET \"/api/v1/skills/{skill}/versions\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Charlie","children":[]},"parameterTypeName":"word"},{"group":{"start":18,"value":"\"/api/v1/skills/{skill}/versions\"","children":[{"start":19,"value":"/api/v1/skills/{skill}/versions","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":36,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 404","stepMatchArguments":[{"group":{"start":34,"value":"404","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":37,"pickleLine":39,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":40,"keywordType":"Action","textWithKeyword":"When Alice calls GET \"/api/v1/skills/{skill}/1.0.0\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Alice","children":[]},"parameterTypeName":"word"},{"group":{"start":16,"value":"\"/api/v1/skills/{skill}/1.0.0\"","children":[{"start":17,"value":"/api/v1/skills/{skill}/1.0.0","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":41,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 200","stepMatchArguments":[{"group":{"start":34,"value":"200","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":42,"pickleLine":44,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":45,"keywordType":"Context","textWithKeyword":"Given Charlie is authenticated but not in Alice's organization","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"When Charlie calls GET \"/api/v1/skills/{skill}/1.0.0\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Charlie","children":[]},"parameterTypeName":"word"},{"group":{"start":18,"value":"\"/api/v1/skills/{skill}/1.0.0\"","children":[{"start":19,"value":"/api/v1/skills/{skill}/1.0.0","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 404","stepMatchArguments":[{"group":{"start":34,"value":"404","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":48,"pickleLine":50,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":51,"keywordType":"Action","textWithKeyword":"When Alice calls GET \"/api/v1/skills/{skill}/1.0.0/files/skills.json\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Alice","children":[]},"parameterTypeName":"word"},{"group":{"start":16,"value":"\"/api/v1/skills/{skill}/1.0.0/files/skills.json\"","children":[{"start":17,"value":"/api/v1/skills/{skill}/1.0.0/files/skills.json","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":52,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 200","stepMatchArguments":[{"group":{"start":34,"value":"200","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":53,"pickleLine":55,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":56,"keywordType":"Context","textWithKeyword":"Given Charlie is authenticated but not in Alice's organization","stepMatchArguments":[]},{"pwStepLine":55,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"When Charlie calls GET \"/api/v1/skills/{skill}/1.0.0/files/skills.json\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Charlie","children":[]},"parameterTypeName":"word"},{"group":{"start":18,"value":"\"/api/v1/skills/{skill}/1.0.0/files/skills.json\"","children":[{"start":19,"value":"/api/v1/skills/{skill}/1.0.0/files/skills.json","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 404","stepMatchArguments":[{"group":{"start":34,"value":"404","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":59,"pickleLine":61,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":60,"gherkinStepLine":62,"keywordType":"Action","textWithKeyword":"When Alice calls GET \"/api/v1/skills/{skill}/star\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Alice","children":[]},"parameterTypeName":"word"},{"group":{"start":16,"value":"\"/api/v1/skills/{skill}/star\"","children":[{"start":17,"value":"/api/v1/skills/{skill}/star","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":63,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 200","stepMatchArguments":[{"group":{"start":34,"value":"200","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":64,"pickleLine":66,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":67,"keywordType":"Context","textWithKeyword":"Given Charlie is authenticated but not in Alice's organization","stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":68,"keywordType":"Action","textWithKeyword":"When Charlie calls GET \"/api/v1/skills/{skill}/star\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Charlie","children":[]},"parameterTypeName":"word"},{"group":{"start":18,"value":"\"/api/v1/skills/{skill}/star\"","children":[{"start":19,"value":"/api/v1/skills/{skill}/star","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":69,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 404","stepMatchArguments":[{"group":{"start":34,"value":"404","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":70,"pickleLine":72,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":73,"keywordType":"Context","textWithKeyword":"Given Charlie is authenticated but not in Alice's organization","stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":74,"keywordType":"Action","textWithKeyword":"When Charlie calls GET \"/api/v1/search?q={searchQuery}\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Charlie","children":[]},"parameterTypeName":"word"},{"group":{"start":18,"value":"\"/api/v1/search?q={searchQuery}\"","children":[{"start":19,"value":"/api/v1/search?q={searchQuery}","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":75,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 200","stepMatchArguments":[{"group":{"start":34,"value":"200","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":74,"gherkinStepLine":76,"keywordType":"Outcome","textWithKeyword":"And the API response body should not contain the private skill name","stepMatchArguments":[]}]},
  {"pwTestLine":77,"pickleLine":79,"tags":["@private-packages","@api-bypass","@critical"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given Alice has published a private skill \"private-access-skill\"","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"private-access-skill\"","children":[{"start":37,"value":"private-access-skill","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":80,"keywordType":"Action","textWithKeyword":"When Alice calls GET \"/api/v1/search?q={searchQuery}\" with auth","stepMatchArguments":[{"group":{"start":0,"value":"Alice","children":[]},"parameterTypeName":"word"},{"group":{"start":16,"value":"\"/api/v1/search?q={searchQuery}\"","children":[{"start":17,"value":"/api/v1/search?q={searchQuery}","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":79,"gherkinStepLine":81,"keywordType":"Outcome","textWithKeyword":"Then the API response status should be 200","stepMatchArguments":[{"group":{"start":34,"value":"200","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":80,"gherkinStepLine":82,"keywordType":"Outcome","textWithKeyword":"And the API response body should contain the private skill name","stepMatchArguments":[]}]},
]; // bdd-data-end