import { skillsJsonSchema, skillsLockSchema } from '@internals/schemas';
import type { Context } from 'hono';
import { Hono } from 'hono';
import { z } from 'zod';

const BASE_URL = 'https://www.tankpkg.dev/api/v1/schemas';

const tankJsonSchema = {
  ...z.toJSONSchema(skillsJsonSchema),
  $id: `${BASE_URL}/tank.json`,
  title: 'Tank Manifest (tank.json)',
  description:
    'Schema for Tank skill package manifest files. Add "$schema": "https://www.tankpkg.dev/api/v1/schemas/tank.json" to your tank.json for editor autocomplete.'
};

const tankLockSchema = {
  ...z.toJSONSchema(skillsLockSchema),
  $id: `${BASE_URL}/tank.lock`,
  title: 'Tank Lockfile (tank.lock)',
  description: 'Schema for Tank skill package lockfiles. Auto-generated by `tank install`.'
};

function serveSchema(c: Context, schema: object) {
  c.header('Content-Type', 'application/schema+json');
  c.header('Cache-Control', 'public, max-age=86400');
  return c.json(schema);
}

export const schemaRoutes = new Hono()
  .get('/schemas/tank.json', (c) => serveSchema(c, tankJsonSchema))
  .get('/schemas/tank.lock', (c) => serveSchema(c, tankLockSchema))
  .get('/schemas/skills.json', (c) => serveSchema(c, tankJsonSchema))
  .get('/schemas/skills.lock', (c) => serveSchema(c, tankLockSchema));
