import { createReadStream, existsSync, statSync } from 'node:fs';
import { Hono } from 'hono';
import { stream } from 'hono/streaming';

const cliRoutes = new Hono();

const BINARY_DIR = '/app/cli-binaries';

const PLATFORMS: Record<string, string> = {
  'linux-x64': 'tank-linux-x64',
  'linux-arm64': 'tank-linux-arm64',
  'darwin-x64': 'tank-darwin-x64',
  'darwin-arm64': 'tank-darwin-arm64',
  'win-x64': 'tank-win-x64.exe'
};

/**
 * GET /cli/download/:platform
 * Serves pre-built CLI binary for the given platform.
 * Only available when TANK_MODE=selfhosted.
 */
cliRoutes.get('/download/:platform', async (c) => {
  if (process.env.TANK_MODE !== 'selfhosted') {
    return c.json({ error: 'Not found' }, 404);
  }

  const platform = c.req.param('platform');
  const filename = PLATFORMS[platform];

  if (!filename) {
    return c.json(
      {
        error: 'Invalid platform',
        available: Object.keys(PLATFORMS)
      },
      400
    );
  }

  const filepath = `${BINARY_DIR}/${filename}`;

  if (!existsSync(filepath)) {
    return c.json({ error: 'Binary not available' }, 404);
  }

  const stat = statSync(filepath);

  c.header('Content-Type', 'application/octet-stream');
  c.header('Content-Disposition', `attachment; filename="tank"`);
  c.header('Content-Length', stat.size.toString());
  c.header('Cache-Control', 'public, max-age=3600');

  return stream(c, async (s) => {
    const readable = createReadStream(filepath);
    for await (const chunk of readable) {
      await s.write(chunk);
    }
  });
});

/**
 * GET /cli/install.sh
 * Returns a shell script that downloads and installs the CLI.
 * The script has the registry URL baked in from APP_URL.
 */
cliRoutes.get('/install.sh', async (c) => {
  if (process.env.TANK_MODE !== 'selfhosted') {
    return c.json({ error: 'Not found' }, 404);
  }

  const appUrl = process.env.APP_URL || process.env.BETTER_AUTH_URL || 'http://localhost:3000';

  const script = `#!/usr/bin/env bash
# Tank CLI Installer
# Generated by ${appUrl}
set -euo pipefail

REGISTRY_URL="${appUrl}"
INSTALL_DIR="\${TANK_INSTALL_DIR:-/usr/local/bin}"

# Detect platform
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)  ARCH="x64" ;;
  aarch64) ARCH="arm64" ;;
  arm64)   ARCH="arm64" ;;
  *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
esac

PLATFORM="\${OS}-\${ARCH}"
echo "Downloading Tank CLI for \${PLATFORM}..."
curl -fsSL "\${REGISTRY_URL}/api/cli/download/\${PLATFORM}" -o /tmp/tank
chmod +x /tmp/tank

# Configure CLI to use this registry
mkdir -p ~/.tank
cat > ~/.tank/config.json << CONF
{
  "registry": "\${REGISTRY_URL}"
}
CONF

# Install
if [ -w "\${INSTALL_DIR}" ]; then
  mv /tmp/tank "\${INSTALL_DIR}/tank"
else
  sudo mv /tmp/tank "\${INSTALL_DIR}/tank"
fi

echo "Tank CLI installed to \${INSTALL_DIR}/tank"
echo "Registry: \${REGISTRY_URL}"
echo ""
echo "Run 'tank login' to authenticate."
`;

  c.header('Content-Type', 'text/plain; charset=utf-8');
  c.header('Content-Disposition', 'attachment; filename="install.sh"');
  return c.body(script);
});

/**
 * GET /cli/platforms
 * Returns available platforms and download URLs.
 */
cliRoutes.get('/platforms', async (c) => {
  if (process.env.TANK_MODE !== 'selfhosted') {
    return c.json({ error: 'Not found' }, 404);
  }

  const appUrl = process.env.APP_URL || process.env.BETTER_AUTH_URL || 'http://localhost:3000';
  const available = Object.entries(PLATFORMS)
    .filter(([_, filename]) => existsSync(`${BINARY_DIR}/${filename}`))
    .map(([platform, filename]) => ({
      platform,
      url: `${appUrl}/api/cli/download/${platform}`,
      size: existsSync(`${BINARY_DIR}/${filename}`) ? statSync(`${BINARY_DIR}/${filename}`).size : 0
    }));

  return c.json({
    installScript: `${appUrl}/api/cli/install.sh`,
    installCommand: `curl -fsSL ${appUrl}/api/cli/install.sh | bash`,
    platforms: available
  });
});

export { cliRoutes };
