#!/usr/bin/env bash
# Tank On-Premises Installation Script
# 
# Usage:
#   git clone https://github.com/tankpkg/tank.git
#   cd tank
#   bash scripts/onprem-install.sh
#
# For air-gapped environments:
#   1. Clone on a machine with internet
#   2. Transfer the repo to the air-gapped machine
#   3. Run this script
#
# This script will:
#   1. Check prerequisites (Docker, Docker Compose)
#   2. Generate a .env file from template
#   3. Build Docker images locally (no external registry needed)
#   4. Start all services
#   5. Wait for health checks
#   6. Print the setup wizard URL
#
# Environment variables (set before running to skip prompts):
#   TANK_ADMIN_EMAIL    - First admin email
#   TANK_ADMIN_PASSWORD - First admin password (min 8 chars)
#   TANK_APP_URL        - Public URL (default: http://localhost:3000)
#   TANK_AUTO           - Set to "true" for fully non-interactive mode

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${BLUE}▸${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${YELLOW}!${NC} $*"; }
error() { echo -e "${RED}✖${NC} $*" >&2; }
fatal() { error "$*"; exit 1; }

COMPOSE_FILE="infra/docker-compose.yml"
ENV_FILE=".env"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$REPO_ROOT"

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║       Tank On-Premises Installation          ║${NC}"
echo -e "${BOLD}║  Security-first package manager for AI skills║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""

# ─── Step 1: Prerequisites ───
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || fatal "Docker is required. Install: https://docs.docker.com/get-docker/"
ok "Docker found: $(docker --version | head -1)"

if docker compose version >/dev/null 2>&1; then
  ok "Docker Compose found: $(docker compose version | head -1)"
  COMPOSE_CMD="docker compose"
elif docker-compose --version >/dev/null 2>&1; then
  ok "Docker Compose found: $(docker-compose --version | head -1)"
  COMPOSE_CMD="docker-compose"
else
  fatal "Docker Compose is required. Install: https://docs.docker.com/compose/install/"
fi

# Check Docker is running
docker info >/dev/null 2>&1 || fatal "Docker daemon is not running. Start Docker and try again."
ok "Docker daemon is running"

# Check compose file exists
[ -f "$COMPOSE_FILE" ] || fatal "Compose file not found: $COMPOSE_FILE. Are you in the Tank repo root?"
ok "Compose file found"

echo ""

# ─── Step 2: Environment Configuration ───
info "Configuring environment..."

if [ -f "$ENV_FILE" ]; then
  warn ".env file already exists"
  if [ "${TANK_AUTO:-}" != "true" ]; then
    read -p "  Overwrite? [y/N] " -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      ok "Keeping existing .env"
    else
      cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%s)"
      ok "Backed up existing .env"
    fi
  fi
fi

# Generate secret if needed
BETTER_AUTH_SECRET=$(grep "^BETTER_AUTH_SECRET=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true)
if [ -z "$BETTER_AUTH_SECRET" ] || [ "$BETTER_AUTH_SECRET" = "your-secret-key-here-change-me" ]; then
  BETTER_AUTH_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)
fi

# Collect configuration
APP_URL="${TANK_APP_URL:-}"
ADMIN_EMAIL="${TANK_ADMIN_EMAIL:-}"
ADMIN_PASSWORD="${TANK_ADMIN_PASSWORD:-}"

if [ "${TANK_AUTO:-}" != "true" ]; then
  if [ -z "$APP_URL" ]; then
    read -p "  Public URL [http://localhost:3000]: " APP_URL
    APP_URL="${APP_URL:-http://localhost:3000}"
  fi
  if [ -z "$ADMIN_EMAIL" ]; then
    read -p "  Admin email: " ADMIN_EMAIL
  fi
  if [ -z "$ADMIN_PASSWORD" ]; then
    read -s -p "  Admin password (min 8 chars): " ADMIN_PASSWORD
    echo ""
  fi
else
  APP_URL="${APP_URL:-http://localhost:3000}"
fi

# Generate .env
cat > "$ENV_FILE" << EOF
# Tank On-Premises Configuration
# Generated by onprem-install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Core ──
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
APP_URL=${APP_URL}
BETTER_AUTH_URL=${APP_URL}

# ── Database ──
POSTGRES_USER=tank
POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)
POSTGRES_DB=tank

# ── Storage (MinIO) ──
STORAGE_BACKEND=s3
MINIO_ROOT_USER=tank
MINIO_ROOT_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)
S3_BUCKET=packages
S3_REGION=us-east-1

# ── Auth ──
AUTH_PROVIDERS=credentials
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=

# ── Admin Bootstrap ──
FIRST_ADMIN_EMAIL=${ADMIN_EMAIL}
FIRST_ADMIN_PASSWORD=${ADMIN_PASSWORD}

# ── Ports ──
APP_PORT=3000
MINIO_CONSOLE_PORT=9001

# ── Scanner LLM (optional) ──
# GROQ_API_KEY=
# OPENROUTER_API_KEY=
# LLM_API_KEY=
# LLM_BASE_URL=
# LLM_MODEL=
EOF

ok "Generated .env file"
echo ""

# ─── Step 3: Build Docker Images ───
info "Building Docker images (this takes 2-5 minutes)..."
$COMPOSE_CMD -f "$COMPOSE_FILE" build --parallel 2>&1 | tail -5
ok "Docker images built"
echo ""

# ─── Step 4: Start Services ───
info "Starting services..."
$COMPOSE_CMD -f "$COMPOSE_FILE" up -d
ok "Services started"
echo ""

# ─── Step 5: Health Checks ───
info "Waiting for services to be ready..."

MAX_WAIT=120
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
  if curl -sf "http://localhost:${APP_PORT:-3000}/api/health" >/dev/null 2>&1; then
    ok "Web app is healthy"
    break
  fi
  sleep 3
  ELAPSED=$((ELAPSED + 3))
  printf "  Waiting... (%ds/%ds)\r" "$ELAPSED" "$MAX_WAIT"
done

if [ $ELAPSED -ge $MAX_WAIT ]; then
  warn "Web app not ready after ${MAX_WAIT}s. Check: $COMPOSE_CMD -f $COMPOSE_FILE logs registry"
fi

# Check scanner
if curl -sf "http://localhost:8000/health" >/dev/null 2>&1; then
  ok "Scanner is healthy"
else
  warn "Scanner not ready (non-critical — scans will fail until it starts)"
fi

echo ""

# ─── Step 6: Summary ───
echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║          Installation Complete!               ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""

if [ -n "$ADMIN_EMAIL" ] && [ -n "$ADMIN_PASSWORD" ]; then
  ok "Admin user will be created on first boot: $ADMIN_EMAIL"
  echo ""
  echo -e "  ${BOLD}Open Tank:${NC} ${APP_URL}"
  echo -e "  ${BOLD}Login:${NC}     ${ADMIN_EMAIL}"
else
  echo -e "  ${BOLD}Setup Wizard:${NC} ${APP_URL}/setup"
  echo ""
  echo "  The wizard will guide you through:"
  echo "    1. Database verification"
  echo "    2. URL configuration"
  echo "    3. Storage setup"
  echo "    4. Admin account creation"
  echo "    5. Auth provider setup"
  echo "    6. Scanner configuration"
fi

echo ""
echo "  Useful commands:"
echo "    View logs:    $COMPOSE_CMD -f $COMPOSE_FILE logs -f"
echo "    Stop:         $COMPOSE_CMD -f $COMPOSE_FILE down"
echo "    Restart:      $COMPOSE_CMD -f $COMPOSE_FILE restart"
echo "    Update:       git pull && $COMPOSE_CMD -f $COMPOSE_FILE build && $COMPOSE_CMD -f $COMPOSE_FILE up -d"
echo ""
echo "  MinIO Console:  http://localhost:${MINIO_CONSOLE_PORT:-9001}"
echo ""
