/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RegistryRouteImport } from './routes/_registry'
import { Route as RegistryIndexRouteImport } from './routes/_registry/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as RegistryLoginRouteImport } from './routes/_registry/login'
import { Route as RegistryCliLoginRouteImport } from './routes/_registry/cli-login'
import { Route as LlmLlmsDottxtRouteImport } from './routes/_llm/llms[.]txt'
import { Route as LlmLlmsFullDottxtRouteImport } from './routes/_llm/llms-full[.]txt'
import { Route as RegistrySkillsIndexRouteImport } from './routes/_registry/skills.index'
import { Route as RegistryDocsIndexRouteImport } from './routes/_registry/docs.index'
import { Route as RegistrySkillsSplatRouteImport } from './routes/_registry/skills.$'
import { Route as RegistryDocsSplatRouteImport } from './routes/_registry/docs.$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/_registry',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistryRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryLoginRoute = RegistryLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RegistryRoute,
} as any)
const RegistryCliLoginRoute = RegistryCliLoginRouteImport.update({
  id: '/cli-login',
  path: '/cli-login',
  getParentRoute: () => RegistryRoute,
} as any)
const LlmLlmsDottxtRoute = LlmLlmsDottxtRouteImport.update({
  id: '/_llm/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmLlmsFullDottxtRoute = LlmLlmsFullDottxtRouteImport.update({
  id: '/_llm/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrySkillsIndexRoute = RegistrySkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => RegistryRoute,
} as any)
const RegistryDocsIndexRoute = RegistryDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => RegistryRoute,
} as any)
const RegistrySkillsSplatRoute = RegistrySkillsSplatRouteImport.update({
  id: '/skills/$',
  path: '/skills/$',
  getParentRoute: () => RegistryRoute,
} as any)
const RegistryDocsSplatRoute = RegistryDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => RegistryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof RegistryIndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/llms-full.txt': typeof LlmLlmsFullDottxtRoute
  '/llms.txt': typeof LlmLlmsDottxtRoute
  '/cli-login': typeof RegistryCliLoginRoute
  '/login': typeof RegistryLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$': typeof RegistryDocsSplatRoute
  '/skills/$': typeof RegistrySkillsSplatRoute
  '/docs/': typeof RegistryDocsIndexRoute
  '/skills/': typeof RegistrySkillsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/llms-full.txt': typeof LlmLlmsFullDottxtRoute
  '/llms.txt': typeof LlmLlmsDottxtRoute
  '/cli-login': typeof RegistryCliLoginRoute
  '/login': typeof RegistryLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof RegistryIndexRoute
  '/docs/$': typeof RegistryDocsSplatRoute
  '/skills/$': typeof RegistrySkillsSplatRoute
  '/docs': typeof RegistryDocsIndexRoute
  '/skills': typeof RegistrySkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_registry': typeof RegistryRouteWithChildren
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/_llm/llms-full.txt': typeof LlmLlmsFullDottxtRoute
  '/_llm/llms.txt': typeof LlmLlmsDottxtRoute
  '/_registry/cli-login': typeof RegistryCliLoginRoute
  '/_registry/login': typeof RegistryLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/_registry/': typeof RegistryIndexRoute
  '/_registry/docs/$': typeof RegistryDocsSplatRoute
  '/_registry/skills/$': typeof RegistrySkillsSplatRoute
  '/_registry/docs/': typeof RegistryDocsIndexRoute
  '/_registry/skills/': typeof RegistrySkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/cli-login'
    | '/login'
    | '/api/$'
    | '/docs/$'
    | '/skills/$'
    | '/docs/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/dashboard'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/cli-login'
    | '/login'
    | '/api/$'
    | '/'
    | '/docs/$'
    | '/skills/$'
    | '/docs'
    | '/skills'
  id:
    | '__root__'
    | '/_registry'
    | '/admin'
    | '/dashboard'
    | '/_llm/llms-full.txt'
    | '/_llm/llms.txt'
    | '/_registry/cli-login'
    | '/_registry/login'
    | '/api/$'
    | '/_registry/'
    | '/_registry/docs/$'
    | '/_registry/skills/$'
    | '/_registry/docs/'
    | '/_registry/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RegistryRoute: typeof RegistryRouteWithChildren
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LlmLlmsFullDottxtRoute: typeof LlmLlmsFullDottxtRoute
  LlmLlmsDottxtRoute: typeof LlmLlmsDottxtRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_registry': {
      id: '/_registry'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_registry/': {
      id: '/_registry/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_registry/login': {
      id: '/_registry/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof RegistryLoginRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/_registry/cli-login': {
      id: '/_registry/cli-login'
      path: '/cli-login'
      fullPath: '/cli-login'
      preLoaderRoute: typeof RegistryCliLoginRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/_llm/llms.txt': {
      id: '/_llm/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_llm/llms-full.txt': {
      id: '/_llm/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_registry/skills/': {
      id: '/_registry/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof RegistrySkillsIndexRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/_registry/docs/': {
      id: '/_registry/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof RegistryDocsIndexRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/_registry/skills/$': {
      id: '/_registry/skills/$'
      path: '/skills/$'
      fullPath: '/skills/$'
      preLoaderRoute: typeof RegistrySkillsSplatRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/_registry/docs/$': {
      id: '/_registry/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof RegistryDocsSplatRouteImport
      parentRoute: typeof RegistryRoute
    }
  }
}

interface RegistryRouteChildren {
  RegistryCliLoginRoute: typeof RegistryCliLoginRoute
  RegistryLoginRoute: typeof RegistryLoginRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  RegistryDocsSplatRoute: typeof RegistryDocsSplatRoute
  RegistrySkillsSplatRoute: typeof RegistrySkillsSplatRoute
  RegistryDocsIndexRoute: typeof RegistryDocsIndexRoute
  RegistrySkillsIndexRoute: typeof RegistrySkillsIndexRoute
}

const RegistryRouteChildren: RegistryRouteChildren = {
  RegistryCliLoginRoute: RegistryCliLoginRoute,
  RegistryLoginRoute: RegistryLoginRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  RegistryDocsSplatRoute: RegistryDocsSplatRoute,
  RegistrySkillsSplatRoute: RegistrySkillsSplatRoute,
  RegistryDocsIndexRoute: RegistryDocsIndexRoute,
  RegistrySkillsIndexRoute: RegistrySkillsIndexRoute,
}

const RegistryRouteWithChildren = RegistryRoute._addFileChildren(
  RegistryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RegistryRoute: RegistryRouteWithChildren,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LlmLlmsFullDottxtRoute: LlmLlmsFullDottxtRoute,
  LlmLlmsDottxtRoute: LlmLlmsDottxtRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
